set_property SRC_FILE_INFO {cfile:{D:/Digital IC Design/Projects/MIPS/MIPS/MIPS.srcs/constrs_1/imports/MIPS/MIPS_constraints.xdc} rfile:../../../MIPS.srcs/constrs_1/imports/MIPS/MIPS_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports rst]
